# Generated by Django 5.1.3 on 2025-01-21 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mysubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subtask', models.CharField(max_length=255, verbose_name='Название подзадачи')),
                ('status', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_mysubtasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysubtasks', to='TM.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'моя подзадача',
                'verbose_name_plural': 'Мои подзадачи',
            },
        ),
    ]
