# Generated by Django 5.1.3 on 2025-01-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0002_mysubtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
    ]
