# Generated by Django 5.1.3 on 2025-01-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0003_subtask_delete_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysubtask',
            name='creator',
        ),
        migrations.AddField(
            model_name='mysubtask',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опмсание задачи'),
        ),
        migrations.AlterField(
            model_name='mysubtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysubtasks', to='TM.mytask', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='due_date',
            field=models.DateField(verbose_name='Срок выполнения'),
        ),
    ]
