# Generated by Django 5.1.3 on 2025-01-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0004_remove_mysubtask_creator_mysubtask_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TM.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
