"""
Django settings for MyProject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f&lk#f4fn55i$zeih)hi&#vn=c$2(=^xv-lcdcgmbkcx$b4)x-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'TM',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR/'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR/'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/main' # По умолчанию Django ищет страницу профиля по адресу /accounts/profile/. но Теперь Django после входа будет перенаправлять на главную страницу.
LOGOUT_REDIRECT_URL = '/' # По умолчанию Django ищет страницу выхода по адресу /accounts/logout/. но Теперь Django после выхода будет перенаправлять на главную страницу.


CELERY_BEAT_SCHEDULE = {
   'check_due_dates_every_day': {
       'task': 'TM.tasks.check_due_dates', # Укажите путь до вашей задачи
       'schedule': crontab(minute='28', hour='03'),  # Запускать в 10:00 каждый день
   },
}

CELERY_TASK_ROUTES = {
    'TM.tasks.*': {'queue': 'celery'},
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'


#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Используем SMTP для отправки
#EMAIL_HOST = 'smtp.inbox.ru'  # Ваш SMTP сервер
#EMAIL_PORT = 587                # Порт SMTP сервера
#EMAIL_USE_TLS = True            # Использовать TLS
#EMAIL_HOST_USER = 'pasha@inbox.ru' # ваш email
#EMAIL_HOST_PASSWORD = ''  # Пароль приложения 
#DEFAULT_FROM_EMAIL = 'pasha@inbox.ru' # Адрес, с которого будут отправляться письма
#SERVER_EMAIL = 'pasha@inbox.ru' # Адрес для отправки сообщений об ошибках

#celery -A MyProject worker -l info
#celery -A MyProject beat -l info


#celery -A TM worker -l info -Q celery,default